using FluentAssertions;
using Project.Base.Domain.Object.Shared;

namespace Project.Base.Tests.Domain;

public class BaseObjectWithIdTests
{
    #region Default Values

    [Fact]
    public void Ctor_ShouldInitializeIdWithDefaultGuid()
    {
        // Don't can generate a ID prop because the ID is generated by the database,
        // so we can only test that the default value is Guid.Empty --> not in database yet,
        // so the default value is Guid.Empty

        // Arrange & Act
        var entity = new TestEntity { Name = "Test", Email = "test@test.com" };

        // Assert
        entity.Id.Should().BeEmpty();
    }

    #endregion

    #region CompareTo

    [Fact]
    public void CompareTo_Null_ShouldReturnPositive()
    {
        // Arrange
        var entity = new TestEntity { Id = Guid.NewGuid() };

        // Act
        var result = entity.CompareTo(null!);

        // Assert
        result.Should().BePositive();
    }

    [Fact]
    public void CompareTo_SameId_ShouldReturnZero()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id };
        var entity2 = new TestEntity { Id = id };

        // Act
        var result = entity1.CompareTo(entity2);

        // Assert
        result.Should().Be(0);
    }

    [Fact]
    public void CompareTo_LesserId_ShouldReturnPositive()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.Parse("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF") };
        var entity2 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000000") };

        // Act
        var result = entity1.CompareTo(entity2);

        // Assert
        result.Should().BePositive();
    }

    [Fact]
    public void CompareTo_GreaterId_ShouldReturnNegativee()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000000") };
        var entity2 = new TestEntity { Id = Guid.Parse("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF") };

        // Act
        var result = entity1.CompareTo(entity2);

        // Assert
        result.Should().BeNegative();
    }

    [Fact]
    public void CompareTo_SortingDescending_ShouldOrderCorrectly()
    {
        // Arrange
        var entities = new List<TestEntity>
        {
            new() { Id = Guid.Parse("00000000-0000-0000-0000-000000000001") },
            new() { Id = Guid.Parse("00000000-0000-0000-0000-000000000003") },
            new() { Id = Guid.Parse("00000000-0000-0000-0000-000000000002") }
        };

        // Act
        entities = entities.OrderByDescending(e => e.Id).ToList();
        var sortedIds = entities.Select(e => e.Id);

        // Assert
        var expectedOrder = new[]
        {
            Guid.Parse("00000000-0000-0000-0000-000000000003"),
            Guid.Parse("00000000-0000-0000-0000-000000000002"),
            Guid.Parse("00000000-0000-0000-0000-000000000001")
        };
        sortedIds.Should().Equal(expectedOrder);
    }

    #endregion

    #region IComparable<BaseObjectWithId>

    [Fact]
    public void ShouldImplementIComparable()
    {
        // Arrange
        var entity = new TestEntity();

        // Act & Assert
        entity.Should().BeAssignableTo<IComparable<TestEntity>>();
    }

    #endregion

    #region Id Property

    [Fact]
    public void Id_ShouldGetAndSet()
    {
        // Arrange
        var entity = new TestEntity { Name = "Test", Email = "test@test.com" };
        var newId = Guid.NewGuid();

        // Act
        entity.Id = newId;
        var gotId = entity.Id;

        // Assert
        gotId.Should().Be(newId);
    }

    [Fact]
    public void Id_ShouldBeIndependentEmpty()
    {
        //The id of object is generated by the database, so we can only test that the default value is Guid.Empty and that two different instances have different Ids.

        // Arrange
        var entity1 = new TestEntity { Name = "Entity1", Email = "e1@test.com" };
        var entity2 = new TestEntity { Name = "Entity2", Email = "e2@test.com" };

        // Act
        var id1 = entity1.Id;
        var id2 = entity2.Id;

        // Assert
        id1.Should().Be(Guid.Empty);
        id2.Should().Be(Guid.Empty);
    }

    #endregion
}
