using FluentAssertions;
using Project.Base.Domain.Object.Shared;

namespace Project.Base.Tests.Domain;

public class BaseObjectWithIdTests
{
    #region Default Values

    [Fact]
    public void Ctor_ShouldInitializeIdWithDefaultGuid()
    {
        // Don't can generate a ID prop because the ID is generated by the database,
        // so we can only test that the default value is Guid.Empty --> not in database yet,
        // so the default value is Guid.Empty

        // Arrange & Act
        var entity = new TestEntity { Name = "Test", Email = "test@test.com" };

        // Assert
        entity.Id.Should().BeEmpty();
    }

    #endregion

    #region CompareTo

    [Fact]
    public void CompareTo_Null_ShouldReturnPositive()
    {
        // Arrange
        var entity = new TestEntity { Id = Guid.NewGuid() };

        // Act
        var result = entity.CompareTo(null!);

        // Assert
        result.Should().BePositive();
    }

    [Fact]
    public void CompareTo_SameId_ShouldReturnZero()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id };
        var entity2 = new TestEntity { Id = id };

        // Act
        var result = entity1.CompareTo(entity2);

        // Assert
        result.Should().Be(0);
    }

    [Fact]
    public void CompareTo_LesserId_ShouldReturnPositive()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.Parse("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF") };
        var entity2 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000000") };

        // Act
        var result = entity1.CompareTo(entity2);

        // Assert
        result.Should().BePositive();
    }

    [Fact]
    public void CompareTo_GreaterId_ShouldReturnNegativee()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000000") };
        var entity2 = new TestEntity { Id = Guid.Parse("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF") };

        // Act
        var result = entity1.CompareTo(entity2);

        // Assert
        result.Should().BeNegative();
    }

    [Fact]
    public void CompareTo_SortingDescending_ShouldOrderCorrectly()
    {
        // Arrange
        var entities = new List<TestEntity>
        {
            new() { Id = Guid.Parse("00000000-0000-0000-0000-000000000001") },
            new() { Id = Guid.Parse("00000000-0000-0000-0000-000000000003") },
            new() { Id = Guid.Parse("00000000-0000-0000-0000-000000000002") }
        };

        // Act
        entities = entities.OrderByDescending(e => e.Id).ToList();
        var sortedIds = entities.Select(e => e.Id);

        // Assert
        var expectedOrder = new[]
        {
            Guid.Parse("00000000-0000-0000-0000-000000000003"),
            Guid.Parse("00000000-0000-0000-0000-000000000002"),
            Guid.Parse("00000000-0000-0000-0000-000000000001")
        };
        sortedIds.Should().Equal(expectedOrder);
    }

    #endregion

    #region IComparable<BaseObjectWithId>

    [Fact]
    public void ShouldImplementIComparable()
    {
        // Arrange
        var entity = new TestEntity();

        // Act & Assert
        entity.Should().BeAssignableTo<IComparable<TestEntity>>();
    }

    #endregion

    #region Id Property

    [Fact]
    public void Id_ShouldGetAndSet()
    {
        // Arrange
        var entity = new TestEntity { Name = "Test", Email = "test@test.com" };
        var newId = Guid.NewGuid();

        // Act
        entity.Id = newId;
        var gotId = entity.Id;

        // Assert
        gotId.Should().Be(newId);
    }

    [Fact]
    public void Id_ShouldBeIndependentEmpty()
    {
        //The id of object is generated by the database, so we can only test that the default value is Guid.Empty and that two different instances have different Ids.

        // Arrange
        var entity1 = new TestEntity { Name = "Entity1", Email = "e1@test.com" };
        var entity2 = new TestEntity { Name = "Entity2", Email = "e2@test.com" };

        // Act
        var id1 = entity1.Id;
        var id2 = entity2.Id;

        // Assert
        id1.Should().Be(Guid.Empty);
        id2.Should().Be(Guid.Empty);
    }

    #endregion

    #region Equals(object?)

    [Fact]
    public void Equals_NullObject_ShouldReturnFalse()
    {
        // Arrange
        var entity = new TestEntity { Id = Guid.NewGuid(), Name = "Test", Email = "test@test.com" };

        // Act
        var result = entity.Equals((object?)null);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public void Equals_DifferentType_ShouldReturnFalse()
    {
        // Arrange
        var entity = new TestEntity { Id = Guid.NewGuid(), Name = "Test", Email = "test@test.com" };
        var otherObject = "not an entity";

        // Act
        var result = entity.Equals(otherObject);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public void Equals_SameInstance_ShouldReturnTrue()
    {
        // Arrange
        var entity = new TestEntity { Id = Guid.NewGuid(), Name = "Test", Email = "test@test.com" };

        // Act
        var result = entity.Equals((object)entity);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void Equals_SameId_DifferentInstances_ShouldReturnTrue()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = entity1.Equals(entity2);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void Equals_DifferentId_ShouldReturnFalse()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.NewGuid(), Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = Guid.NewGuid(), Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = entity1.Equals(entity2);

        // Assert
        result.Should().BeFalse();
    }

    #endregion

    #region GetHashCode

    [Fact]
    public void GetHashCode_ShouldReturnConsistentHashCode()
    {
        // Arrange
        var entity = new TestEntity { Id = Guid.NewGuid(), Name = "Test", Email = "test@test.com" };
        var hashCode1 = entity.GetHashCode();
        var hashCode2 = entity.GetHashCode();

        // Act & Assert
        hashCode1.Should().Be(hashCode2);
    }

    [Fact]
    public void GetHashCode_SameId_ShouldReturnSameHashCode()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };

        // Act
        var hashCode1 = entity1.GetHashCode();
        var hashCode2 = entity2.GetHashCode();

        // Assert
        hashCode1.Should().Be(hashCode2);
    }

    [Fact]
    public void GetHashCode_UseInHashSet_ShouldWork()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };
        var hashSet = new HashSet<TestEntity> { entity1 };

        // Act
        var contains = hashSet.Contains(entity2);

        // Assert
        contains.Should().BeTrue();
    }

    #endregion

    #region Equality Operators

    [Fact]
    public void EqualOperator_SameId_ShouldReturnTrue()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = (entity1 == entity2);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void EqualOperator_DifferentId_ShouldReturnFalse()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.NewGuid(), Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = Guid.NewGuid(), Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = (entity1 == entity2);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public void EqualOperator_BothNull_ShouldReturnTrue()
    {
        // Arrange
        TestEntity? entity1 = null;
        TestEntity? entity2 = null;

        // Act
        var result = (entity1 == entity2);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void EqualOperator_LeftNull_ShouldReturnFalse()
    {
        // Arrange
        TestEntity? entity1 = null;
        var entity2 = new TestEntity { Id = Guid.NewGuid(), Name = "Test", Email = "test@test.com" };

        // Act
        var result = (entity1 == entity2);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public void EqualOperator_RightNull_ShouldReturnFalse()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.NewGuid(), Name = "Test", Email = "test@test.com" };
        TestEntity? entity2 = null;

        // Act
        var result = (entity1 == entity2);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public void NotEqualOperator_DifferentId_ShouldReturnTrue()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.NewGuid(), Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = Guid.NewGuid(), Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = (entity1 != entity2);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void NotEqualOperator_SameId_ShouldReturnFalse()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = (entity1 != entity2);

        // Assert
        result.Should().BeFalse();
    }

    #endregion

    #region Comparison Operators

    [Fact]
    public void GreaterThanOperator_ShouldReturnCorrectResult()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000003") };
        var entity2 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000001") };

        // Act
        var result = entity1 > entity2;

        // Assert
        result.Should().BeTrue(); // ascending: higher GUID is greater
    }

    [Fact]
    public void LessThanOperator_ShouldReturnCorrectResult()
    {
        // Arrange
        var entity1 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000001") };
        var entity2 = new TestEntity { Id = Guid.Parse("00000000-0000-0000-0000-000000000003") };

        // Act
        var result = entity1 < entity2;

        // Assert
        result.Should().BeTrue(); // ascending: lower GUID is less
    }

    [Fact]
    public void GreaterThanOrEqualOperator_SameId_ShouldReturnTrue()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = entity1 >= entity2;

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public void LessThanOrEqualOperator_SameId_ShouldReturnTrue()
    {
        // Arrange
        var id = Guid.NewGuid();
        var entity1 = new TestEntity { Id = id, Name = "Test1", Email = "test1@test.com" };
        var entity2 = new TestEntity { Id = id, Name = "Test2", Email = "test2@test.com" };

        // Act
        var result = entity1 <= entity2;

        // Assert
        result.Should().BeTrue();
    }

    #endregion
}
