<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <IsPackable>true</IsPackable>
    <PackageId>Project.Base.Domain</PackageId>
    <Version>1.0.0</Version>
    <Authors>Leonardo Pereira Cabral</Authors>
    <Company>Project.Base</Company>
    <Description>Project.Base.Domain - Serviços, validadores e conversores base para Project.Base library</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/leonardopereira10/Project.Base</PackageProjectUrl>
    <RepositoryUrl>https://github.com/leonardopereira10/Project.Base</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>dotnet c# services validators converters base</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
    <None Include="..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.12.0" />
    <PackageReference Include="Mapster" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.Base.Contracts\Project.Base.Contracts.csproj" />
  </ItemGroup>

</Project>
