<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <PackageId>Project.Base.WebApi</PackageId>
    <Version>1.0.002</Version>
    <Authors>Leonardo Pereira Cabral</Authors>
    <Company>Project.Base</Company>
    <Description>Project.Base.WebApi - Controlador base genérico e utilitários para ASP.NET Core Web APIs com Project.Base library</Description>
    <PackageProjectUrl>https://github.com/leonardopereira10/Project.Base</PackageProjectUrl>
    <RepositoryUrl>https://github.com/leonardopereira10/Project.Base</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>dotnet c# aspnetcore webapi controller base</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>1.0.002</AssemblyVersion>
    <FileVersion>1.0.002</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.Base.Domain\Project.Base.Domain.csproj" />
  </ItemGroup>

</Project>
