<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <IsPackable>true</IsPackable>
    <PackageId>Project.Base.Enumerators</PackageId>
    <Version>1.0.0</Version>
    <Authors>Leonardo Pereira Cabral</Authors>
    <Company>Project.Base</Company>
    <Description>Project.Base.Enumerators - Enumeradores base para Project.Base library</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/leonardopereira10/Project.Base</PackageProjectUrl>
    <RepositoryUrl>https://github.com/leonardopereira10/Project.Base</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>dotnet c# enumerators base</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Globalization.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Globalization.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Globalization.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Globalization.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
