<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
    <IsPackable>true</IsPackable>
    <PackageId>Project.Base.Contracts</PackageId>
    <Version>1.0.002</Version>
    <Authors>Leonardo Pereira Cabral</Authors>
    <Company>Project.Base</Company>
    <Description>Project.Base.Contracts - Contratos (DTO, modelos) base para Project.Base library</Description>
    <PackageProjectUrl>https://github.com/leonardopereira10/Project.Base</PackageProjectUrl>
    <RepositoryUrl>https://github.com/leonardopereira10/Project.Base</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>dotnet c# dto contracts models base</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>1.0.002</AssemblyVersion>
    <FileVersion>1.0.002</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.Base.Enumerators\Project.Base.Enumerators.csproj" />
  </ItemGroup>

</Project>
